export enum Vegetables {
  Carrot = 'Καρότο',
  Broccoli = 'Μπρόκολο',
  Cauliflower = 'Κουνουπίδι',
  Spinach = 'Σπανάκι',
  Cabbage = 'Λάχανο',
  Onion = 'Κρεμμύδι',
  GreenOnion = 'Φρέσκο κρεμμυδάκι',
  Garlic = 'Σκόρδο',
  Pepper = 'Πιπεριά',
  FlorinaPepper = 'Πιπεριά φλωρίνης',
  Tomato = 'Τομάτα',
  CherryTomato = 'Ντοματίνια',
  Cucumber = 'Αγγούρι',
  Eggplant = 'Μελιτζάνα',
  GreenBeans = 'Φασολάκια',
  Potato = 'Πατάτα',
  SweetPotato = 'Γλυκοπατάτα',
  Zucchini = 'Κολοκυθάκια',
  Pumpkin = 'Κολοκύθα',
  Radish = 'Ραπανάκι',
  Beetroot = 'Παντζάρι',
  Lettuce = 'Μαρούλι',
  Arugula = 'Ρόκα',
  Artichoke = 'Αγκινάρα',
  Mushrooms = 'Μανιτάρια',
  Leek = 'Πράσο',
  Celery = 'Σέλινο',
  Endive = 'Ραδίκια',
}
export enum VegetablesEN {
  Carrot = 'Carrot',
  Broccoli = 'Broccoli',
  Cauliflower = 'Cauliflower',
  Spinach = 'Spinach',
  Cabbage = 'Cabbage',
  Onion = 'Onion',
  GreenOnion = 'Green onion',
  Garlic = 'Garlic',
  Pepper = 'Bell pepper',
  FlorinaPepper = 'Florina pepper',
  Tomato = 'Tomato',
  CherryTomato = 'Cherry tomato',
  Cucumber = 'Cucumber',
  Eggplant = 'Eggplant',
  GreenBeans = 'Green beans',
  Potato = 'Potato',
  SweetPotato = 'Sweet potato',
  Zucchini = 'Zucchini',
  Pumpkin = 'Pumpkin',
  Radish = 'Radish',
  Beetroot = 'Beetroot',
  Lettuce = 'Lettuce',
  Arugula = 'Arugula',
  Artichoke = 'Artichoke',
  Mushrooms = 'Mushrooms',
  Leek = 'Leek',
  Celery = 'Celery',
  Endive = 'Chicory',
}

export enum Fruits {
  Lemon = 'Λεμόνι',
  Lime = 'Λάιμ',
  Orange = 'Πορτοκάλι',
  Mandarin = 'Μανταρίνι',
  Grapefruit = 'Γκρέιπφρουτ',
  Strawberry = 'Φράουλα',
  Raspberry = 'Βατόμουρο',
  Blueberry = 'Μύρτιλο',
  Peach = 'Ροδάκινο',
  Apricot = 'Βερίκοκο',
  Cherry = 'Κεράσι',
  Banana = 'Μπανάνα',
  Watermelon = 'Καρπούζι',
  Melon = 'Πεπόνι',
  Apple = 'Μήλο',
  Pear = 'Αχλάδι',
  Pomegranate = 'Ρόδι',
  Fig = 'Σύκο',
  Grape = 'Σταφύλι',
  Raisins = 'Σταφίδες',
  Plum = 'Δαμάσκηνο',
  Medlar = 'Μούσμουλο',
  Pineapple = 'Ανανάς',
  Mango = 'Μάνγκο',
  Cranberry = 'Κράνμπερι',
}
export enum FruitsEN {
  Lemon = 'Lemon',
  Lime = 'Lime',
  Orange = 'Orange',
  Mandarin = 'Mandarin',
  Grapefruit = 'Grapefruit',
  Strawberry = 'Strawberry',
  Raspberry = 'Raspberry',
  Blueberry = 'Blueberry',
  Peach = 'Peach',
  Apricot = 'Apricot',
  Cherry = 'Cherry',
  Banana = 'Banana',
  Watermelon = 'Watermelon',
  Melon = 'Melon',
  Apple = 'Apple',
  Pear = 'Pear',
  Pomegranate = 'Pomegranate',
  Fig = 'Fig',
  Grape = 'Grape',
  Raisins = 'Raisins',
  Plum = 'Plum',
  Medlar = 'Medlar',
  Pineapple = 'Pineapple',
  Mango = 'Mango',
  Cranberry = 'Cranberry',
}

export enum Grain {
  Rice = 'Ρύζι',
  RiceBasmati = 'Ρύζι μπασμάτι',
  Oats = 'Βρώμη',
  Corn = 'Καλαμπόκι',
  Semolina = 'Σιμιγδάλι',
  Bulgur = 'Πλιγούρι',
  Trahanas = 'Τραχανάς',
  Couscous = 'Κούσκους',
  Quinoa = 'Κινόα',
  WholeWheatFlour = 'Αλεύρι ολικής',
  Flour = 'Αλεύρι',
  Spaghetti = 'Σπαγγέτι',
  Penne = 'Πέννες',
  Orzo = 'Κριθαράκι',
  Hilopites = 'Χυλοπίτες',
  Lasagna = 'Λαζάνια',
  PitaBread = 'Ψωμί Πίτα',
  Bread = 'Ψωμί',
  Rusks = 'Παξιμάδια',
  PhylloSheet = 'Φύλλο κρούστας',
  Cornmeal = 'Αλεύρι καλαμποκιού',
}
export enum GrainEN {
  Rice = 'Rice',
  RiceBasmati = 'Basmati rice',
  Oats = 'Oats',
  Corn = 'Corn',
  Semolina = 'Semolina',
  Bulgur = 'Bulgur',
  Trahanas = 'Trahanas',
  Couscous = 'Couscous',
  Quinoa = 'Quinoa',
  WholeWheatFlour = 'Whole wheat flour',
  Flour = 'Flour',
  Spaghetti = 'Spaghetti',
  Penne = 'Penne',
  Orzo = 'Orzo',
  Hilopites = 'Hilopites',
  Lasagna = 'Lasagna',
  PitaBread = 'Pita bread',
  Bread = 'Bread',
  Rusks = 'Rusks',
  PhylloSheet = 'Phyllo sheet',
  Cornmeal = 'Cornmeal',
}

export enum Dairy {
  Eggs = 'Αυγά',
  Milk = 'Γάλα',
  GreekYogurt = 'Γιαούρτι',
  CowYogurt = 'Γιαούρτι αγελαδινό',
  Cream = 'Κρέμα γάλακτος',
  CreamCheese = 'Τυρί κρέμα',
  Butter = 'Βούτυρο',
  FetaCheese = 'Φέτα',
  GravieraCheese = 'Γραβιέρα',
  KefalotyriCheese = 'Κεφαλοτύρι',
  KasseriCheese = 'Κασέρι',
  MizithraCheese = 'Μυζήθρα',
  AnthotyroCheese = 'Ανθότυρο',
  Mozzarella = 'Μοτσαρέλα',
  Parmesan = 'Παρμεζάνα',
  CottageCheese = 'Τυρί cottage',
  Condensed_Milk = 'Ζαχαρούχο γάλα',
  EvaporatedMilk = 'Γάλα εβαπορέ',
}
export enum DairyEN {
  Eggs = 'Eggs',
  Milk = 'Milk',
  GreekYogurt = 'Yogurt',
  CowYogurt = 'Cow Yogurt',
  Cream = 'Heavy Cream',
  CreamCheese = 'Cream cheese',
  Butter = 'Butter',
  FetaCheese = 'Feta cheese',
  GravieraCheese = 'Graviera cheese',
  KefalotyriCheese = 'Kefalotyri cheese',
  KasseriCheese = 'Kasseri cheese',
  MizithraCheese = 'Mizithra cheese',
  AnthotyroCheese = 'Anthotyro cheese',
  Mozzarella = 'Mozzarella',
  Parmesan = 'Parmesan',
  CottageCheese = 'Cottage cheese',
  Condensed_Milk = 'Condensed milk',
  EvaporatedMilk = 'Evaporated milk',
}

export enum Meat {
  Lamb = 'Αρνί',
  LambMinced = 'Κιμάς αρνίσιος',
  Beef = 'Μοσχάρι',
  BeefMinced = 'Κιμάς μοσχαρίσιος',
  Pork = 'Χοιρινό',
  Bacon = 'Μπέικον',
  Sausage = 'Λουκάνικο',
  Chicken = 'Κοτόπουλο',
  Turkey = 'Γαλοπούλα',
  Duck = 'Πάπια',
  Rabbit = 'Κουνέλι',
  Goat = 'Κατσίκι',
  Salmon = 'Σολομός',
  SeaBass = 'Λαβράκι',
  SeaBream = 'Τσιπούρα',
  Cod = 'Μπακαλιάρος',
  Tuna = 'Τόνος',
  Sardines = 'Σαρδέλες',
  Anchovies = 'Γαύρος',
  Mackerel = 'Σκουμπρί',
  Octopus = 'Χταπόδι',
  Calamari = 'Καλαμάρι',
  Shrimp = 'Γαρίδες',
  Mussels = 'Μύδια',
  Cuttlefish = 'Σουπιά',
  Crab = 'Καβούρι',
}
export enum MeatEN {
  Lamb = 'Lamb',
  LambMinced = 'Minced λamb',
  Beef = 'Beef',
  BeefMinced = 'Minced βeef',
  Pork = 'Pork',
  Bacon = 'Bacon',
  Sausage = 'Sausage',
  Chicken = 'Chicken',
  Turkey = 'Turkey',
  Duck = 'Duck',
  Rabbit = 'Rabbit',
  Goat = 'Goat',
  Salmon = 'Salmon',
  SeaBass = 'Sea Bass',
  SeaBream = 'Sea Bream',
  Cod = 'Cod',
  Tuna = 'Tuna',
  Sardines = 'Sardines',
  Anchovies = 'Anchovies',
  Mackerel = 'Mackerel',
  Octopus = 'Octopus',
  Calamari = 'Calamari',
  Shrimp = 'Shrimp',
  Mussels = 'Mussels',
  Cuttlefish = 'Cuttlefish',
  Crab = 'Crab',
}

export enum Lipid {
  OliveOil = 'Ελαιόλαδο',
  ExtraVirginOliveOil = 'Εξαιρετικό παρθένο ελαιόλαδο',
  SunflowerOil = 'Ηλιέλαιο',
  CornOil = 'Αραβοσιτέλαιο',
  Tahini = 'Ταχίνι',
  Margarine = 'Μαργαρίνη',
  Avocado = 'Αβοκάντο',
  OlivesGreen = 'Ελιές',
  Mayonnaise = 'Μαγιονέζα',
  Almonds = 'Αμύγδαλα',
  Walnuts = 'Καρύδια',
  Sesame = 'Σουσάμι',
}
export enum LipidEN {
  OliveOil = 'Olive oil',
  ExtraVirginOliveOil = 'Extra virgin olive oil',
  SunflowerOil = 'Sunflower oil',
  CornOil = 'Corn oil',
  Tahini = 'Tahini',
  Margarine = 'Margarine',
  Avocado = 'Avocado',
  OlivesGreen = 'Olives',
  Mayonnaise = 'Mayonnaise',
  Almonds = 'Almonds',
  Walnuts = 'Walnuts',
  Sesame = 'Sesame',
}

export enum Legumes {
  Lentils = 'Φακές',
  Chickpeas = 'Ρεβύθια',
  FavaBeans = 'Κουκιά',
  Fava = 'Φάβα',
  BlackEyedPeas = 'Μαυρομάτικα',
  WhiteBeans = 'Φασόλια λευκά',
  GigantesBeans = 'Φασόλια γίγαντες',
  RedKidneyBeans = 'Φασόλια κόκκινα',
  BlackBeans = 'Φασόλια μαύρα',
  GreenPeas = 'Αρακάς',
  Soybeans = 'Σόγια',
}
export enum LegumesEN {
  Lentils = 'Lentils',
  Chickpeas = 'Chickpeas',
  FavaBeans = 'Fava beans',
  Fava = 'Fava',
  BlackEyedPeas = 'Black-Eyed peas',
  WhiteBeans = 'White beans',
  GigantesBeans = 'Gigantes beans',
  RedKidneyBeans = 'Red kidney beans',
  BlackBeans = 'Black beans',
  GreenPeas = 'Green peas',
  Soybeans = 'Soybeans',
}

export enum Pastry {
  Sugar = 'Ζάχαρη',
  BrownSugar = 'Καστανή ζάχαρη',
  PowderSugar = 'Ζάχαρη άχνη',
  Honey = 'Μέλι',
  ThymeHoney = 'Μέλι θυμαρίσιο',
  MapleSyrup = 'Σιρόπι σφενδάμου',
  Vanilla = 'Βανίλια',
  Cocoa = 'Κακάο',
  Chocolate = 'Σοκολάτα',
  DarkChocolate = 'Κουβερτούρα',
  Caramel = 'Καραμέλα',
  Jam = 'Μαρμελάδα',
  Mastic = 'Μαστίχα',
  BakingPowder = 'Μπέικιν πάουντερ',
  BakingSoda = 'Σόδα μαγειρικής',
  Yeast = 'Μαγιά',
  Cornstarch = 'Κορν φλάουρ',
}
export enum PastryEN {
  Sugar = 'Sugar',
  BrownSugar = 'Brown sugar',
  PowderSugar = 'Powdered sugar',
  Honey = 'Honey',
  ThymeHoney = 'Thyme honey',
  MapleSyrup = 'Maple syrup',
  Vanilla = 'Vanilla',
  Cocoa = 'Cocoa',
  Chocolate = 'Chocolate',
  DarkChocolate = 'Dark chocolate',
  Caramel = 'Caramel',
  Jam = 'Jam',
  Mastic = 'Mastic',
  BakingPowder = 'Baking powder',
  BakingSoda = 'Baking soda',
  Yeast = 'Yeast',
  Cornstarch = 'Cornstarch',
}

export enum Spices {
  Salt = 'Αλάτι',
  BlackPepper = 'Μαύρο πιπέρι',
  Oregano = 'Ρίγανη',
  Thyme = 'Θυμάρι',
  Rosemary = 'Δεντρολίβανο',
  Dill = 'Άνηθος',
  Basil = 'Βασιλικός',
  Parsley = 'Μαϊντανός',
  Mint = 'Δυόσμος',
  Cinnamon = 'Κανέλα',
  Cumin = 'Κύμινο',
  Paprika = 'Πάπρικα',
  SmokeyPaprika = 'Πάπρικα καπνιστή',
  RedPepperFlakes = 'Μπούκοβο',
  BayLeaves = 'Φύλλα δάφνης',
  Turmeric = 'Κουρκουμάς',
  Sumac = 'Σουμάκ',
  Anise = 'Γλυκάνισος',
  Cloves = 'Γαρύφαλλο',
  Nutmeg = 'Μοσχοκάρυδο',
  Chives = 'Σχοινόπρασο',
}
export enum SpicesEN {
  Salt = 'Salt',
  BlackPepper = 'Black pepper',
  Oregano = 'Oregano',
  Thyme = 'Thyme',
  Rosemary = 'Rosemary',
  Dill = 'Dill',
  Basil = 'Basil',
  Parsley = 'Parsley',
  Mint = 'Mint',
  Cinnamon = 'Cinnamon',
  Cumin = 'Cumin',
  Paprika = 'Paprika',
  SmokeyPaprika = 'Smoked paprika',
  RedPepperFlakes = 'Red pepper flakes',
  BayLeaves = 'Bay leaves',
  Turmeric = 'Turmeric',
  Sumac = 'Sumac',
  Anise = 'Anise',
  Cloves = 'Cloves',
  Nutmeg = 'Nutmeg',
  Chives = 'Chives',
}
