// Each Greek enum stays as-is (used for el values)
// Add a matching English enum with the same keys

export enum Vegetables {
  Carrot = 'Καρότο',
  Broccoli = 'Μπρόκολο',
  Cauliflower = 'Κουνουπίδι',
  Spinach = 'Σπανάκι',
  Cabbage = 'Λάχανο',
  Onion = 'Κρεμμύδι',
  Garlic = 'Σκόρδο',
  Pepper = 'Πιπεριά',
  Tomato = 'Τομάτα',
  Cucumber = 'Αγγούρι',
  Eggplant = 'Μελιτζάνα',
  GreenBeans = 'Φασολάκια',
  Potato = 'Πατάτα',
  Zucchini = 'Κολοκυθάκια',
  SweetPotato = 'Γλυκοπατάτα',
  Radish = 'Ραπανάκι',
  Lettuce = 'Μαρούλι',
  Artichoke = 'Αγγινάρα',
  Mushrooms = 'Μανιτάρια',
  Leek = 'Πράσο',
  Celery = 'Σέλινο',
}
export enum VegetablesEN {
  Carrot = 'Carrot',
  Broccoli = 'Broccoli',
  Cauliflower = 'Cauliflower',
  Spinach = 'Spinach',
  Cabbage = 'Cabbage',
  Onion = 'Onion',
  Garlic = 'Garlic',
  Pepper = 'Pepper',
  Tomato = 'Tomato',
  Cucumber = 'Cucumber',
  Eggplant = 'Eggplant',
  GreenBeans = 'Green Beans',
  Potato = 'Potato',
  Zucchini = 'Zucchini',
  SweetPotato = 'Sweet Potato',
  Radish = 'Radish',
  Lettuce = 'Lettuce',
  Artichoke = 'Artichoke',
  Mushrooms = 'Mushrooms',
  Leek = 'Leek',
  Celery = 'Celery',
}

export enum Spices {
  Oregano = 'Ρίγανη',
  Thyme = 'Θυμάρι',
  Rosemary = 'Δεντρολίβανο',
  Dill = 'Άνηθο',
  Basil = 'Βασιλικός',
  Cinnamon = 'Κανέλα',
  Parsley = 'Μαϊντανός',
  Coriander = 'Κορίανδρος',
  RedPepperFlakes = 'Μπούκοβο',
  Paprika = 'Πάπρικα',
  Cumin = 'Κύμινο',
  BayLeaves = 'Φύλλα Δάφνης',
  Mint = 'Μέντα',
}
export enum SpicesEN {
  Oregano = 'Oregano',
  Thyme = 'Thyme',
  Rosemary = 'Rosemary',
  Dill = 'Dill',
  Basil = 'Basil',
  Cinnamon = 'Cinnamon',
  Parsley = 'Parsley',
  Coriander = 'Coriander',
  RedPepperFlakes = 'Red Pepper Flakes',
  Paprika = 'Paprika',
  Cumin = 'Cumin',
  BayLeaves = 'Bay Leaves',
  Mint = 'Mint',
}

export enum Fruits {
  Lemon = 'Λεμόνι',
  Orange = 'Πορτοκάλι',
  Grapefruit = 'Πορτοκάλι γλυκό',
  Strawberry = 'Φράουλα',
  Raspberry = 'Βατόμουρο',
  Blueberry = 'Μύρτιλο',
  Peach = 'Ροδάκινο',
  Apricot = 'Βερίκοκο',
  Cherry = 'Κεράσι',
  Banana = 'Μπανάνα',
  Pineapple = 'Ανανάς',
  Mango = 'Μάνγκο',
  Watermelon = 'Καρπούζι',
  Apple = 'Μήλο',
  Pear = 'Άχλαδι',
  Pomegranate = 'Ρόδι',
  Fig = 'Σύκο',
  Cranberry = 'Κράνμπερι',
  Raisins = 'Σταφίδες',
}
export enum FruitsEN {
  Lemon = 'Lemon',
  Orange = 'Orange',
  Grapefruit = 'Grapefruit',
  Strawberry = 'Strawberry',
  Raspberry = 'Raspberry',
  Blueberry = 'Blueberry',
  Peach = 'Peach',
  Apricot = 'Apricot',
  Cherry = 'Cherry',
  Banana = 'Banana',
  Pineapple = 'Pineapple',
  Mango = 'Mango',
  Watermelon = 'Watermelon',
  Apple = 'Apple',
  Pear = 'Pear',
  Pomegranate = 'Pomegranate',
  Fig = 'Fig',
  Cranberry = 'Cranberry',
  Raisins = 'Raisins',
}

export enum Grain {
  Barley = 'Κριθάρι',
  Rice = 'Ρύζι',
  Corn = 'Καλαμπόκι',
  Oats = 'Βρώμη',
  Quinoa = 'Κινόα',
  Couscous = 'Κούσκους',
  Amaranth = 'Αμάρανθος',
  Cereal = 'Δημητριακά',
  Flour = 'Αλεύρι',
  Bread = 'Ψωμί',
  Pasta = 'Ζυμαρικά',
}
export enum GrainEN {
  Barley = 'Barley',
  Rice = 'Rice',
  Corn = 'Corn',
  Oats = 'Oats',
  Quinoa = 'Quinoa',
  Couscous = 'Couscous',
  Amaranth = 'Amaranth',
  Cereal = 'Cereal',
  Flour = 'Flour',
  Bread = 'Bread',
  Pasta = 'Pasta',
}

export enum Dairy {
  FetaCheese = 'Φέτα',
  KefalotyriCheese = 'Κεφαλοτύρι',
  MizithraCheese = 'Μυζήθρα',
  GravieraCheese = 'Γραβιέρα',
  AnthotyroCheese = 'Ανθότυρο',
  KasseriCheese = 'Κασέρι',
  GreekYogurt = 'Ελληνικό Γιαούρτι',
  Tzatziki = 'Τζατζίκι',
  Milk = 'Γάλα',
  Butter = 'Βούτυρο',
  Cream = 'Κρέμα Γάλακτος',
}
export enum DairyEN {
  FetaCheese = 'Feta Cheese',
  KefalotyriCheese = 'Kefalotyri Cheese',
  MizithraCheese = 'Mizithra Cheese',
  GravieraCheese = 'Graviera Cheese',
  AnthotyroCheese = 'Anthotyro Cheese',
  KasseriCheese = 'Kasseri Cheese',
  GreekYogurt = 'Greek Yogurt',
  Tzatziki = 'Tzatziki',
  Milk = 'Milk',
  Butter = 'Butter',
  Cream = 'Heavy Cream',
}

export enum Meat {
  Lamb = 'Αρνί',
  Beef = 'Μοσχάρι',
  Pork = 'Χοιρινό',
  Chicken = 'Κοτόπουλο',
  Veal = 'Μοσχαρίσιο',
  Rabbit = 'Κουνέλι',
  Goat = 'Κατσίκι',
  Venison = 'Αγριογούρουνο',
  Duck = 'Πάπια',
  Quail = 'Πέρδικα',
  Turkey = 'Γαλοπούλα',
  Octopus = 'Χταπόδι',
  Calamari = 'Καλαμάρι',
  Sardines = 'Σαρδέλες',
  Anchovies = 'Γαύρος',
  Mackerel = 'Σκουμπρί',
  Cod = 'Μπακαλιάρος',
  SeaBass = 'Λαβράκι',
  Tuna = 'Τόνος',
  Shrimp = 'Γαρίδες',
  Mussels = 'Μύδια',
}
export enum MeatEN {
  Lamb = 'Lamb',
  Beef = 'Beef',
  Pork = 'Pork',
  Chicken = 'Chicken',
  Veal = 'Veal',
  Rabbit = 'Rabbit',
  Goat = 'Goat',
  Venison = 'Wild Boar',
  Duck = 'Duck',
  Quail = 'Quail',
  Turkey = 'Turkey',
  Octopus = 'Octopus',
  Calamari = 'Calamari',
  Sardines = 'Sardines',
  Anchovies = 'Anchovies',
  Mackerel = 'Mackerel',
  Cod = 'Cod',
  SeaBass = 'Sea Bass',
  Tuna = 'Tuna',
  Shrimp = 'Shrimp',
  Mussels = 'Mussels',
}

export enum Lipid {
  OliveOil = 'Λάδι Ελιάς',
  VegetableOil = 'Λάδι Φυτικό',
  SunflowerOil = 'Λάδι Ηλίου',
  SesameOil = 'Λάδι Σουσαμιού',
  Butter = 'Βούτυρο',
  ClarifiedButter = 'Καθαρισμένο Βούτυρο (Γκι)',
  Tahini = 'Ταχίνι',
}
export enum LipidEN {
  OliveOil = 'Olive Oil',
  VegetableOil = 'Vegetable Oil',
  SunflowerOil = 'Sunflower Oil',
  SesameOil = 'Sesame Oil',
  Butter = 'Butter',
  ClarifiedButter = 'Clarified Butter (Ghee)',
  Tahini = 'Tahini',
}

export enum Legumes {
  Lentils = 'Φακές',
  Chickpeas = 'Ρεβύθια',
  FavaBeans = 'Κουκιά',
  BlackEyedPeas = 'Μαυρομάτικα',
  WhiteBeans = 'Φασόλια Τρεμοπούλι',
  GigantesBeans = 'Φασόλια Γίγαντες',
  GreenPeas = 'Αρακάς',
  YellowSplitPeas = 'Φακή Κίτρινη Χωριστή',
  Cowpeas = 'Κουρκουτιά',
}
export enum LegumesEN {
  Lentils = 'Lentils',
  Chickpeas = 'Chickpeas',
  FavaBeans = 'Fava Beans',
  BlackEyedPeas = 'Black-Eyed Peas',
  WhiteBeans = 'White Beans',
  GigantesBeans = 'Gigantes Beans',
  GreenPeas = 'Green Peas',
  YellowSplitPeas = 'Yellow Split Peas',
  Cowpeas = 'Cowpeas',
}

export enum Pastry {
  Sugar = 'Ζάχαρη',
  Honey = 'Μέλι',
  Chocolate = 'Σοκολάτα',
  Truffles = 'Τρούφες',
}
export enum PastryEN {
  Sugar = 'Sugar',
  Honey = 'Honey',
  Chocolate = 'Chocolate',
  Truffles = 'Truffles',
}
